version: "3"
services:
  front:
    image: node:14.15.4-buster-slim
    volumes:
      - ./front:/usr/src
      - front_modules:/usr/src/node_modules #node_modulesはコンテナ内部で用意します
    working_dir: "/usr/src"
    command: sh -c "yarn install && yarn start"
    ports:
      - "80:3000"
    environment:
      REACT_APP_SERVER_URL: "http://localhost:3000"
  api:
    image: node:14.15.4-buster-slim
    volumes:
      - ./api/:/usr/src/
      - api_modules:/usr/src/node_modules #node_modulesはコンテナ内部で用意します
    working_dir: "/usr/src"
    ports:
      - "3000:3000"
    command: sh -c "yarn install && yarn dev"
    depends_on:
      - seleniumhub
    environment:
      CLIENT_ORIGIN_URL: "http://localhost"
  seleniumhub:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    shm_size: 2gb

  # chrome:
  #   image: selenium/node-chrome:4.0.0-beta-1-20210215
  #   volumes:
  #     - /dev/shm:/dev/shm
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     - SE_EVENT_BUS_HOST=selenium-hub
  #     - SE_EVENT_BUS_PUBLISH_PORT=4442
  #     - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  #   ports:
  #     - "6900:5900"

  # edge:
  #   image: selenium/node-edge:4.0.0-beta-1-20210215
  #   volumes:
  #     - /dev/shm:/dev/shm
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     - SE_EVENT_BUS_HOST=selenium-hub
  #     - SE_EVENT_BUS_PUBLISH_PORT=4442
  #     - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  #   ports:
  #     - "6901:5900"

  # firefox:
  #   image: selenium/node-firefox:4.0.0-beta-1-20210215
  #   volumes:
  #     - /dev/shm:/dev/shm
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     - SE_EVENT_BUS_HOST=selenium-hub
  #     - SE_EVENT_BUS_PUBLISH_PORT=4442
  #     - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  #   ports:
  #     - "6902:5900"

  # opera:
  #   image: selenium/node-opera:4.0.0-beta-1-20210215
  #   volumes:
  #     - /dev/shm:/dev/shm
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     - SE_EVENT_BUS_HOST=selenium-hub
  #     - SE_EVENT_BUS_PUBLISH_PORT=4442
  #     - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  #   ports:
  #     - "6903:5900"

  # selenium-hub:
  #   image: selenium/hub:4.0.0-beta-1-20210215
  #   container_name: selenium-hub
  #   ports:
  #     - "4442:4442"
  #     - "4443:4443"
  #     - "4444:4444"
volumes:
  front_modules:
  api_modules:
